config/routes.rb
Rails.application.routes.draw do

    root 'pages#home'
    get 'home/about', to: 'pages#about'
    get 'signup', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    

    resources :articles
    resources :users, except: [:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  
  validates :title, presence: true, length: {maximum: 20, minimum: 3}
  validates :description, presence: true, length: {maximum: 250, minimum: 3}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many  :articles, dependent: :destroy
  has_secure_password
  
  
  before_save {self.email = email.downcase}
  
  validates :username,presence: true, 
            length: {minimum: 3, maximum: 25}, 
            uniqueness: {case_sensitive: false}
  validates :email, presence: true, 
            length: {minimum:3, maximum: 105},
            uniqueness: {case_sensitive: false},
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password_digest, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  
  
  def logged_in?
    !!current_user
  end
  
  def require_login
    if !logged_in
      flash[:danger] = "That action requires you to be logged in"
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_filter :check_for_cancel, only: [:create,:update]
    # controller checks for login sessions still pending
  
  def index
    @articles = Article.all.paginate(page: params[:page], per_page: 2)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    find_article
  end
  
  def update
    find_article
    if @article.update(article_permit_params)
      flash[:success] = "Article successfully Updated"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end
  
  
  def create
    @article = Article.new(article_permit_params)
    @article.user = current_user
    
    if @article.save
      flash[:success] = "Article successfully Created"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end
  
  def destroy
    find_article
    @article.destroy
    redirect_to articles_path
  end
  
  def show
    @article = find_article
  end

  
  
  private
  
    def article_permit_params
      params.require(:article).permit(:title, :description)
    end
    
    def find_article
       @article = Article.find(params[:id])
    end
    
    def check_for_cancel
       redirect_to articles_path if params[:cancel]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in #{user.username}"
      redirect_to user_path(user)
    elsif
      flash.now[:danger] ="Something wrong with your login. Please check credentials"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id]=nil
    flash[:success]="You have successfully logged out"
    redirect_to articles_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_cancel, only: [:create, :update]
  # controller checks for login sessions still pending
  
  def index
    @users = User.all.paginate(page: params[:page], per_page: 2)
  end
  
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(user_permit_params)
    if @user.save
      flash[:success] = "Welcome to the blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
    find_user
  end
  
  def show
    find_user
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end
  
  def update
    find_user
    if @user.update(user_permit_params)
      flash[:success] = "#{@user.username} information successfully changed"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end
  
  def destroy
    find_user
    @user.destroy
    flash[:success] = "User and associated articles successfully deleted"
    redirect_to users_path
  end
  
  private
  
  def user_permit_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def find_user
    @user = User.find(params[:id])
  end
  
  def check_for_cancel
    redirect_to articles_path if params[:cancel]
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {'success'=> 'alert-success', 'notice'=> 'alert-info', 'danger'=> 'alert-danger', 'error'=> 'alert-danger', 'alert'=> 'alert-block'}[flash_type] || flash_type.to_s
    # Does not work {success: 'alert-success', notice: 'alert-info', error: 'alert-error', alert: 'alert-block'}[flash_type] || flash_type.to_s
  
  end
  

end

app/views/articles/_form.html.erb
<%= render 'shared/error_messages', obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html=>{class: "form-horizontal", role: "form"}) do |f|%>
      <div class="form-group row-xs-2">
        <div class="col-xs-2 col-xs-offset-2">
          <%= f.label "Title", class:"form-label"  %> 
        </div> 
        <div class="col-xs-5">
          <%= f.text_field :title, class: "form-control"   %> 
        </div>
      </div>
      
      <div class="form-group row-xs-10">
        <div class="col-xs-2 col-xs-offset-2">
          <%= f.label "Description", class:"form-label"  %> 
        </div>
        <div class="col-xs-5">
          <%= f.text_area :description, class:"form-control", rows: 12 %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-xs-offset-4 col-xs-8">
          <%= f.submit class:"btn btn-primary" %>
          <%= button_tag 'Cancel', class:"btn btn-primary", type: "submit", name: "cancel" %>
        </div>
      </div>
    
    <% end %>

  </div>
</div>

app/views/articles/edit.html.erb
<div align='center'>
  <h1> Edit the Article</h1>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<div align='center'>
  <h2> Listing all Articles :</h2>
   <%= will_paginate %>
</div>  

<div class="col-xs-8 col-xs-offset-2">
  <% @articles.each do |article| %> 
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-large" >
        <div class="article-title">
          <%= article.title %>
        </div>
        <div class="article-body">
          <%= article.description %>
        </div>
        
        <div class="article-actions">
          <%= link_to "Show", article_path(article), 
            class:"btn btn-primary btn-lrg" %>
          <% if current_user == article.user %>
              <%= link_to "Edit", edit_article_path(article),
                  class:"btn btn-warning btn-lrg" %>
              <%= link_to "Delete", article_path(article), 
                  class:"btn btn-danger btn-lrg", 
                  method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>  
        </div>
        <div class="article-meta-details">
          <small> 
            created by: <%= article.user.username if article.user %> , 
            <%= time_ago_in_words(article.created_at) %>  ago,
            <%= time_ago_in_words(article.updated_at) %>  ago
          </small>
        </div>
      
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="col-xs-12" align='center'>
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div align='center'>
  <h1> Add a New Article</h1>
</div>
  <%= render 'form' %>

app/views/articles/show.html.erb
<div class="row col-xs-offset-3">
  <div class="well col-xs-8">
    <% if @article.user %>
      <p> Created by : <%= link_to @article.user.username, user_path(@article.user) %> </p>
    <% end %>
    
    <div class="article-title">
      <strong>Title: </strong>
      <%= @article.title %><br>
    </div>
    
    <div class="article-body">
      <strong>Description: </strong> 
      <%= @article.description %> <br>
    </div>
    <% if current_user == @article.user %>
      <div class="article-actions">
        <%= link_to "Delete", article_path(@article), class:"btn btn-primary btn-lrg", method: :delete, data: {confirm: "Are you sure you want to delete?"} %> 
        <%= link_to "Edit Article", edit_article_path, class:"btn btn-warning btn-lrg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_feedback_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% flash.each do |type,message| %>
       <div class="alert alert-dismissable <%= bootstrap_class_for(type) %> fade in" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_feedback.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% flash.each do |type,message| %>
       <div class="alert alert-dismissable <%= bootstrap_class_for(type) %> fade in" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Brand", root_path, class:"navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %> <span class="sr-only">(current)</span> </li>
        <li><%= link_to "Users", users_path %> <span class="sr-only">(current)</span> </li>
        <li><a href="#">Link</a></li>
        <li class="dropdown <%='disabled' if logged_in? %>" >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Actions 
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to 'New Article', new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
                aria-expanded="false"><span class="glyphicon glyphicon-user icon-size"></span> <strong><%= current_user.username %></strong><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_path(session[:user_id]) %></li>
              <li><%= link_to 'View Profile', user_path(session[:user_id]) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'logout', logout_path(session[:user_id]), method: :delete, class: 'btn btn-block btn-lrg btn-danger' %></li>
            </ul> 
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/flash_feedback' %>
<%= yield %>

<!--only for debugging development-->
<div class="col-xs-8 col-xs-offset-2">
  <%= debug(params) if Rails.env.development? %> 
</div>
<!--only for debugging development-->

</body>
</html>

app/views/pages/about.html.erb
<h1> About page</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Hello, welcome to the home page!</h1>
    <p><%= link_to 'About', home_about_path, class:"btn btn-primary btn-lrg", role:"button" %>
      <%= link_to 'Sign in', signup_path, class:"btn btn-primary btn-lrg", role:"button" %></p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <div class="panel-title">
          <h3>Action could not be completed for the following <%= pluralize(obj.errors.count, "reason")%>:</h3>
        </div>
      </div>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error_messages', obj: @user %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html=>{class: "form-horizontal", role: "form"}) do |f|%>
      <div class="form-group row-xs-2">
        <div class="col-xs-1 col-xs-offset-3">
          <%= f.label "Username", class:"form-label"  %> 
        </div> 
        <div class="col-xs-5">
          <%= f.text_field :username, class: "form-control"   %> 
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-xs-1 col-xs-offset-3">
          <%= f.label "Email", class:"form-label"  %> 
        </div>
        <div class="col-xs-5">
          <%= f.text_field :email, class:"form-control" %>
        </div>
      </div>

      <div class="form-group">  
        <div class="col-xs-1 col-xs-offset-3">
          <%= f.label "Password", class:"form-label"  %> 
        </div>
        <div class="col-xs-5">
          <%= f.text_field :password, class:"form-control", rows: 12 %>
        </div>
      </div>
      
      <div class="form-group">
        <div class='col-xs-offset-4'>
          <%= f.submit(@user.new_record? ? 'Sign up':'Update Account', class:"btn btn-primary") %>
          <%= button_tag 'Cancel', class:"btn btn-primary", type: "submit", name: "cancel" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div align='center'>
  <h1> Edit your user account for the blog</h1>
</div>
  <%= render 'form' %>

app/views/users/index.html.erb
<div align='center'>
  <h2> Listing all Users :</h2>
  <%= will_paginate @users %>
</div>
<% @users.each do |user| %> 
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-large" >
      <div class="article-title">
        <%= link_to user.username, user_path(user) %>
      </div>
      <div class="article-body">
        <%= user.email %>
      </div>
      <% if current_user == user %>
        <div class="article-actions">
          <%= link_to "Show", user_path(user), 
              class:"btn btn-primary btn-lrg" %>
          <%= link_to "Edit", edit_user_path(user),
              class:"btn btn-warning btn-lrg" %>
          <%= link_to "Delete", user_path(user), 
              class:"btn btn-danger btn-lrg", 
              method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>
<div align='center'>
  <%= will_paginate @uses %>
</div>

app/views/users/new.html.erb
<div align='center'>
    <h1> Signup for the blog</h1>
</div>  
    <%= render 'form' %>

app/views/users/show.html.erb
<div align='center'>
  <h2> Listing <%= pluralize(@user.articles.count, "Article") %>  by <%= @user.username %></h2>
  <%= will_paginate @user_articles%>
</div>
<% @user_articles.each do |article| %> 
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-large" >
      <div class="article-title">
        <%= article.title %>
      </div>
      <div class="article-body">
        <%= article.description %>
      </div>
      <% if current_user == @user %>
        <div class="article-actions">
          <%= link_to "Show", article_path(article), 
              class:"btn btn-primary btn-lrg" %>
          <%= link_to "Edit", edit_article_path(article),
              class:"btn btn-warning btn-lrg" %>
          <%= link_to "Delete", article_path(article), 
              class:"btn btn-danger btn-lrg", 
              method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
      <% end %>
      <div class="article-meta-details">
        <small> 
          created <%= time_ago_in_words(article.created_at) %>  ago,
          <%= time_ago_in_words(article.updated_at) %>  ago
        </small>
      </div>
    
    </div>
  </div>
</div>
<% end %>
<div align='center'>
  <%= will_paginate @user_articles%>
</div>
  